### ISSUE TITLE
Bubbles module v2

### ISSUE THREAD

**Issue by scsirdx** [buzzn/module-bubbles#17]
Decoupled data fetching, physics calculation, view.
See buzzn/display-app #55

**Comment by dottorer** [comment]
@scsirdx Can we add an effort estimate for this? I this time boxed work as research or already for the new bubble design?

**Comment by dottorer** [comment]
Still missing:
* code cleanup
* some algorithm improvements

**Comment by dottorer** [comment]
@scsirdx Is this done in this iteration?
